'use client';

import { motion, type Variants } from 'framer-motion';
import { ArrowRight } from 'lucide-react';
import { cn } from '@/lib/utils';

// ─── Lead profile data ────────────────────────────────────────────────────────
const LEAD = {
  company: 'Harbor Logistics Ltd.',
  submittedAt: '3 min ago',
  score: 94,
  tier: 'Enterprise',
  aeAssigned: 'Sarah Chen · ENT-West',
  fields: [
    { label: 'Industry',   value: 'Logistics & Supply Chain' },
    { label: 'Company',    value: '600 employees'            },
    { label: 'Budget',     value: '$80,000 – $100,000'       },
    { label: 'Timeline',   value: 'Before November 2026'     },
    { label: 'Pain',       value: 'Legacy system causing operational loss' },
    { label: 'Tech',       value: 'SAP integration required'  },
    { label: 'Next step',  value: 'Demo requested — call next week' },
  ] as const,
  signals: ['High urgency', 'Budget stated', 'Decision-maker', 'Demo intent'],
};

// ─── Score ring (SVG) ─────────────────────────────────────────────────────────
function ScoreRing({ score }: { score: number }) {
  const r = 28;
  const circ = 2 * Math.PI * r;
  const dash = (score / 100) * circ;

  return (
    <div className="relative flex items-center justify-center" aria-label={`Lead score ${score} out of 100`}>
      <svg width={72} height={72} className="-rotate-90">
        <circle cx={36} cy={36} r={r} fill="none" className="stroke-border" strokeWidth={4} />
        <motion.circle
          cx={36}
          cy={36}
          r={r}
          fill="none"
          className="stroke-primary"
          strokeWidth={4}
          strokeLinecap="round"
          strokeDasharray={circ}
          initial={{ strokeDashoffset: circ }}
          whileInView={{ strokeDashoffset: circ - dash }}
          viewport={{ once: true }}
          transition={{ duration: 1, delay: 0.3, ease: [0.22, 1, 0.36, 1] }}
        />
      </svg>
      <div className="absolute flex flex-col items-center">
        <span className="font-mono text-xl font-bold text-foreground leading-none">{score}</span>
        <span className="font-mono text-[9px] text-muted-foreground">/ 100</span>
      </div>
    </div>
  );
}

// ─── Variants ─────────────────────────────────────────────────────────────────
const containerVariants: Variants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.06 } },
};

const itemVariants: Variants = {
  hidden:  { opacity: 0, y: 8 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.35, ease: 'easeOut' } },
};

// ─── Lead card ────────────────────────────────────────────────────────────────
function LeadBrief() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-80px' }}
      transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
      className="mx-auto max-w-2xl rounded-2xl border border-border bg-card shadow-xl"
      role="article"
      aria-label="Example lead brief generated by AI"
    >
      {/* Header bar */}
      <div className="flex items-center justify-between rounded-t-2xl border-b border-border bg-muted/30 px-6 py-3.5">
        <div className="flex flex-col">
          <span className="font-mono text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
            Lead Brief
          </span>
          <span className="text-sm font-semibold text-foreground">{LEAD.company}</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="font-mono text-[11px] text-muted-foreground">{LEAD.submittedAt}</span>
          <span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/10 px-2.5 py-0.5">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
            <span className="font-mono text-[10px] font-bold text-emerald-500 uppercase tracking-wider">
              Qualified
            </span>
          </span>
        </div>
      </div>

      {/* Body */}
      <div className="flex flex-col gap-0 divide-y divide-border">
        {/* Score + tier row */}
        <div className="flex items-center gap-6 px-6 py-5">
          <ScoreRing score={LEAD.score} />
          <div className="flex flex-col gap-1">
            <span className="text-[11px] font-medium uppercase tracking-widest text-muted-foreground">
              Lead Quality
            </span>
            <span className="text-2xl font-bold tracking-tight text-foreground">
              {LEAD.score}/100
            </span>
            <div className="mt-1 flex flex-wrap gap-1.5">
              {LEAD.signals.map((s) => (
                <span
                  key={s}
                  className="inline-flex items-center rounded-md border border-primary/20 bg-primary/8 px-2 py-0.5 font-mono text-[10px] text-primary"
                >
                  {s}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Field rows */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid grid-cols-1 px-6 py-4 sm:grid-cols-2"
        >
          {LEAD.fields.map(({ label, value }) => (
            <motion.div
              key={label}
              variants={itemVariants}
              className="flex flex-col gap-0.5 py-2.5"
            >
              <span className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
                {label}
              </span>
              <span className="text-[0.875rem] font-medium text-foreground">{value}</span>
            </motion.div>
          ))}
        </motion.div>

        {/* Assignment footer */}
        <div className="flex items-center justify-between rounded-b-2xl bg-primary/[0.03] px-6 py-4">
          <div className="flex flex-col gap-0.5">
            <span className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
              Assigned to
            </span>
            <span className="text-sm font-semibold text-foreground">{LEAD.aeAssigned}</span>
          </div>
          <div className="flex items-center gap-1.5 text-xs font-medium text-primary">
            <span>Gmail delivered</span>
            <ArrowRight className="size-3.5" />
          </div>
        </div>
      </div>
    </motion.div>
  );
}

// ─── Section ──────────────────────────────────────────────────────────────────
export function ExampleQualificationSection() {
  return (
    <section
      id="example"
      className="border-t border-border py-28 px-5 sm:px-8"
      aria-labelledby="example-heading"
    >
      <div className="mx-auto max-w-6xl">
        {/* Header */}
        <div className="mb-14 flex flex-col items-center gap-3 text-center">
          <span className="font-mono text-[11px] font-semibold uppercase tracking-[0.12em] text-primary">
            Example Output
          </span>
          <h2
            id="example-heading"
            className="max-w-lg text-3xl font-semibold leading-tight tracking-[-0.025em] text-foreground sm:text-4xl"
          >
            What your sales team actually receives.
          </h2>
          <p className={cn(
            'max-w-md text-[0.9375rem] text-muted-foreground leading-relaxed'
          )}>
            Not a raw form dump. A fully structured, scored, and routed lead brief — ready for the first call.
          </p>
        </div>

        <LeadBrief />
      </div>
    </section>
  );
}
